version: '2'
services:
    facebook-app:
        image: facebook
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://facebook-mysql:3306/facebook?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9595:9595
    facebook-mysql:
        extends:
            file: mysql.yml
            service: facebook-mysql
